CREATE TABLE IF NOT EXISTS email_outbox (
  id UUID NOT NULL,
  status VARCHAR(20) NOT NULL,
  scheduled_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  PRIMARY KEY (id),
  CHECK (status IN ('NEW', 'PROCESSING', 'SUCCESS', 'FAILED'))
);
